### ISSUE TITLE
node-install.bash: unexpected end of file

### ISSUE THREAD

**Issue by tknobi** [bevry/awesome-travis#2]
I'm trying to use your scripts in a docpad plugin, but i get this error message:

`/home/travis/.travis/job_stages: eval: line 114: syntax error: unexpected end of file`

See log:
https://travis-ci.org/knoblochtobias/docpad-plugin-imagedimensions/jobs/294163327

**Comment by patuf** [comment]
The error seems to be trivial - an `else` statement used, instead of `fi` on row 31 in node-install.bash
